* Nimacs
  Purpose of this project is to allow extending GNU Emacs with Nim as an
  alternative to Elisp.
  
  For module to work with GNU Emacs, you must accept the GPL compatible license
  requirement by passing flag =-d:acceptGPL= when compiling emacs module.
  Without this, GNU Emacs will refuse to load the module.
  
* Prerequisites
  This module requires =emacs-module.h= header file, which is found in emacs
  source. Currently it has to be included manually with switch:
  =-cincludes:PATH_TO_INCLUDE_DIR=.

  By default GNU Emacs dynamic module support might be disabled. In order to
  enable this feature, Emacs has to be compiled from source using
  =--with-modules= flag when configuring it.
  
* Status
  * [X] Emacs function definition wrapper
  * [X] Emacs function call wrapper
  * [-] Emacs literals creation and acquiration
    * [X] Strings
    * [X] Integers
    * [ ] Floats
    * [ ] Vectors
  * [ ] Retrieve EmacsValue type
  * [ ] Support for passing custom Nim objects to Emacs(user_ptr)
  * [ ] Emacs function error handling
